#!/bin/sh

SELF_DIR="$(cd "$(dirname "$0")" && pwd)"
ARIA_LIB_DIR="${ARIA_LIB_DIR:-${SELF_DIR}/lib}"
RUST_MIN_STACK=16777216

cargo install cargo-pgo && rustup component add llvm-tools-preview

output=$(cargo pgo build -- --profile pgo 2>&1)

aria_bin=$(printf "%s\n" "$output" | sed -n 's/.* Now run \(.*\/aria\) on your workload.*/\1/p')

# TODO: write a more interesting benchmark workload
RUST_MIN_STACK=${RUST_MIN_STACK} ARIA_LIB_DIR=${ARIA_LIB_DIR} ${aria_bin} ${SELF_DIR}/examples/sieve.aria

cargo pgo optimize build -- --profile pgo

aria_parent=$(dirname "$aria_bin")
json=false
for arg in "$@"; do
    if [ "$arg" = "--json" ]; then json=true; break; fi
done

# emit JSON so that automated tools can process the path to the optimized binary
# e.g. path=`jq -r '.output_path' /path/to/json.out`
if [ "$json" = true ]; then
    printf '{"output_path":"%s"}\n' "$aria_parent"
else
    printf 'Run PGO optimized Aria as ARIA_LIB_DIR="%s" %s\n' "${ARIA_LIB_DIR}" "${aria_bin}"
fi
