name: SlashClippy

on:
  issue_comment:
    types: [created]

permissions:
  contents: write
  issues: write
  pull-requests: read

jobs:
  dispatch:
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, '/clippy') }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.SLASH_COMMAND_PAT }}
          reaction-token: ${{ secrets.SLASH_COMMAND_PAT }}
          commands: clippy
          dispatch-type: repository
          issue-type: pull-request
          repository: ${{ github.repository }}
